# Generated by Django 4.2.5 on 2023-09-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='date_start',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('New', 'NEW'), ('In Progress', 'IN_PROGRESS'), ('Paused', 'PAUSED'), ('Completed', 'COMPLETED'), ('Deprecated', 'DEPRECATED')], default='New', max_length=16),
        ),
    ]
